### ISSUE TITLE
Webapp fails looking for deploy_flask_app_bastion_host_required_packages

### ISSUE THREAD

**Issue by nlwmn** [redhat-cop/cloud.aws_ops#110]
```
task path: /runner/project/playbooks/webapp/webapp.yaml:2
fatal: [localhost]: FAILED! => {
    "argument_errors": [
        "missing required arguments: deploy_flask_app_bastion_host_required_packages, deploy_flask_app_git_repository, deploy_flask_app_local_registry_port, deploy_flask_app_local_registry_pwd, deploy_flask_app_local_registry_user, deploy_flask_app_rds_info, deploy_flask_app_vm_info"
    ],
``````

**Comment by HichamMourad** [comment]
TASK [cloud.aws_ops.deploy_flask_app : Validating arguments against arg spec 'main' - Deploy flask app in AWS.] ***
task path: /runner/project/playbooks/webapp/webapp.yaml:2
fatal: [localhost]: FAILED! => {
    "argument_errors": [
        "missing required arguments: deploy_flask_app_bastion_host_required_packages, deploy_flask_app_git_repository, deploy_flask_app_local_registry_port, deploy_flask_app_local_registry_pwd, deploy_flask_app_local_registry_user, deploy_flask_app_rds_info, deploy_flask_app_vm_info"
    ],
    "argument_spec_data": {
        "deploy_flask_app_bastion_host_name": {
            "description": "Name for the EC2 instance.",
            "required": true,
            "type": "str"
        },
        "deploy_flask_app_bastion_host_required_packages": {
            "description": "Packages to be installed on the bastion host.",
            "elements": "str",
            "required": true,
            "type": "list"
        },
        "deploy_flask_app_bastion_host…
PLAY RECAP *********************************************************************
localhost                  : ok=55   changed=1    unreachable=0    failed=1    skipped=25   rescued=0    ignored=0

**Comment by abikouo** [comment]
@nlwmn could you please provide the following details:
- The playbook you are using to call the `cloud.aws_ops.webapp.webapp`
- The execution environment details: cloud.aws_ops version deployed into the execution environment

Thanks

**Comment by HichamMourad** [comment]
The playbook being called in controller is:  https://github.com/redhat-cop/cloud.aws_ops/blob/main/playbooks/webapp/webapp.yaml

The Execution environment.  Here is the image [quay.io/abikouo1/ee/cloud-awsops:1.0.0](http://quay.io/abikouo1/ee/cloud-awsops:1.0.0)

We also noticed the Delete operations does NOT delete the Elastic IP created during the create operation.

**Comment by GomathiselviS** [comment]
Hi @nlwmn @HichamMourad Can you please try the playbook with an execution environment that includes the latest cloud.aws_ops collection (2.0.0) collection?

**Comment by GomathiselviS** [comment]
Hi @HichamMourad  @nlwmn Any update on this?

**Comment by GomathiselviS** [comment]
We're marking this ticket as resolved since it functions as intended with the most recent collection version. If you have any differing observations, feel free to reopen the issue.
