### ISSUE TITLE
Roles with missing integration tests

### ISSUE THREAD

**Issue by alinabuzachis** [redhat-cop/cloud.aws_ops#14]
##### SUMMARY

Roles not covered by integration tests:

- [ ] ec2_instance_terminate_by_tag

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by jillr** [comment]
@alinabuzachis Is this addressed by the new tests here? https://github.com/redhat-cop/cloud.aws_ops/tree/main/tests/integration/targets/test_ec2_instance_terminate_by_tag
