### ISSUE TITLE
Add support for scale-up and scale-down for the webapp playbook

### ISSUE THREAD

**Issue by abikouo** [redhat-cop/cloud.aws_ops#4]
Currently the webapp is not scalable, we cannot reduce nor increase the number workers of the application.
This should be available as done for Azure
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

playbooks/webapp.yaml

**Comment by jillr** [comment]
We are creating new use cases that add different types of application scaling to the webapp scenarios based on customer feedback, I think that would cover the need to offer scaling options for this role.
