### ISSUE TITLE
aws default/vars won't work in automation controller

### ISSUE THREAD

**Issue by IPvSean** [redhat-cop/cloud.aws_ops#82]
this won't work-> 
https://github.com/redhat-cop/cloud.aws_ops/blob/main/playbooks/webapp/webapp.yaml#L22

with automation controller because you would use a AWS credential which uses environment variables.

**Comment by jillr** [comment]
The team will test if https://github.com/redhat-cop/cloud.aws_ops/pull/87 has addressed the issue

**Comment by gravesm** [comment]
This has been verified to be working after #87.
