### ISSUE TITLE
Amazon RDS for PostgreSQL version 14.2 no longer supported

### ISSUE THREAD

**Issue by ghoelzer-aws** [redhat-cop/cloud.aws_ops#90]
By chance I was looking for some good AWS/Red Hat demos for the Minneapolis RHUG in September, and came across this repo.  In experimenting with your Webapp Playbook I discovered that the PostgresSQL RDS Engine version you are referencing, 14.2 is no longer supported.  Please bump the version to 14.3 or higher, see the following for currently supported versions - https://docs.aws.amazon.com/AmazonRDS/latest/PostgreSQLReleaseNotes/postgresql-release-calendar.html

I'm happy to submit a pull request if that would be easier, but thanks for all your good work!

**Comment by hakbailey** [comment]
@ghoelzer-aws thank you for filing this issue! There is [an open PR](https://github.com/redhat-cop/cloud.aws_ops/pull/86) that includes this change, it should be fixed once that merges.

**Comment by jillr** [comment]
fixed-by: #86
